### ISSUE TITLE
Add staking pallet to Pangolin & Crab

### ISSUE THREAD

**Issue by jiguantong** [darwinia-network/darwinia-2.0#104]
- [ ] https://github.com/darwinia-network/darwinia-2.0/pull/68
- [ ] https://github.com/darwinia-network/darwinia-2.0/pull/81

**Comment by AsceticBear** [comment]
Remember to add the staking and deposit precompiles BTW.check out https://github.com/darwinia-network/darwinia-2.0/pull/81/commits/8bb1711c1b4c564f748627056ed2efcdee1c0e49
