### ISSUE TITLE
Build the new genesis base on Darwinia 1.0's latest block

### ISSUE THREAD

**Issue by jiguantong** [darwinia-network/darwinia-2.0#106]
https://github.com/darwinia-network/darwinia-2.0/blob/main/node/src/chain_spec/darwinia.rs#L215

**Comment by AurevoirXavier** [comment]
What do you mean?

**Comment by jiguantong** [comment]
> What do you mean?

This todo: https://github.com/darwinia-network/darwinia-2.0/blob/main/node/src/chain_spec/darwinia.rs#L226

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia-2.0/blob/756fcaff85b1ec9acd713344d1728107dd08552d/node/src/chain_spec/darwinia.rs#L226

**Comment by AurevoirXavier** [comment]
The new state is quite large. Maybe I won't put it in the code directly.
