### ISSUE TITLE
`ECDSA` vs `Sr25519` as chain's native account type

### ISSUE THREAD

**Issue by AsceticBear** [darwinia-network/darwinia-2.0#15]
### Advantages
- No need to distinguish Smart Chain and Chain.
- Most of the time, you will only need one wallet, i.e. Metamask.
### Disadvantages
- Maintaining numerous precompiles can introduce complexity, as well as security concerns.
- Polkadot wallets are not supported. As Substrate devolves, more and more people and developers may start using PolkadotJS to implement things. We may be more awkward at that time.

### Advantages
- ?
### Disadvantages
- Two wallets, PolkadotJS and Metamask.

**Comment by AurevoirXavier** [comment]
We might need a pallet for claiming the old multi-sig addresses.

**Comment by jiguantong** [comment]
https://github.com/darwinia-network/darwinia-2.0/issues/47
