### ISSUE TITLE
Dispatch precompile compatibility support

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-2.0#185]
https://github.com/darwinia-network/darwinia-2.0/blob/5bb61bfc479562ba40573e8eee2cdfadeaee7003/precompile/dispatch/src/lib.rs#L52

Support old style.

**Comment by hackfisher** [comment]
For the s2s message sdk compatibility, different pallet id allocations/changes could also cause incompatibilities? @wuminzhe @xiaoch05

**Comment by xiaoch05** [comment]
The pallet id of bridge message and remote evm pallet will impact sdk, also the index of the call.
