### ISSUE TITLE
Check account ref

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-2.0#187]
The ref should be updated correctly.
- storage added after migration
- storage dropped after migration

**Comment by boundless-forest** [comment]
- For those accounts that participate in the session module, its consumers increase by 1.  The session storage has been discard in 2.0, the consumers should update too.
```sh
 [
    [
      2rhmFReHdFzmGF8kB6WpF83KTJNEnLYcjyf5wdMKkzEawmF7
    ]
    {
      nonce: 0
      consumers: 3
      providers: 1
      sufficients: 1
      data: {
        free: 515,083,479,579,824,805,539,659
        reserved: 0
        miscFrozen: 0
        feeFrozen: 0
      }
    }
  ]
```

**Comment by boundless-forest** [comment]
- For those bonded accounts in the staking pallet, its consumers increase by 1. The bond state will be discarded in the 2.0, the original ledger data goes to `darwinia-deposit` and `darwinia-staking` pallets.  The thing here is much more complicated than I imagined, the consumers will increase by 1 in the darwinia-deposit `lock` and darwinia-staking `stake`. A simple way is sub consumers by 1 in the state process when detecting the bond accounts, then we adjust consumers in the account-migration migrate process.

**Comment by AurevoirXavier** [comment]
Or we could rebuild the ref count. Like what we have done in #240.
