### ISSUE TITLE
The `AssetDetails` type updated in `v0.9.36`

### ISSUE THREAD

**Issue by boundless-forest** [darwinia-network/darwinia-2.0#232]
https://github.dev/paritytech/substrate/blob/cb4f2491b00af7d7817f3a54209c26b20faa1f51/frame/assets/src/migration.rs#L27

The state processor rely on this struct, adoption needs here.

**Comment by AurevoirXavier** [comment]
This was already listed in #193.

Check `E1-runtimemigration` for more information.

**Comment by boundless-forest** [comment]
I am aware of this. The main purpose of this issue is to avoid forgetting to update the state processor.
