### ISSUE TITLE
Pallet Storage Migration List

### ISSUE THREAD

**Issue by boundless-forest** [darwinia-network/darwinia-2.0#26]
## Migration needed
- [x] (System: frame_system::Pallet)
- [x] (Indices: pallet_indices::Pallet)
- [x] (Balances: darwinia_balances::<Instance1>::Pallet)
- [x] (Kton: darwinia_balances::<Instance2>::Pallet)
- [x] (Staking: darwinia_staking::Pallet)
- [x] (Identity: pallet_identity::Pallet)
- [x] (Vesting: pallet_vesting::Pallet)
- [x] (Proxy: pallet_proxy::Pallet)
- [x] (EVM: darwinia_evm::Pallet) https://github.com/darwinia-network/darwinia-2.0/issues/14
- [x] (Ethereum: darwinia_ethereum::Pallet) https://github.com/darwinia-network/darwinia-2.0/issues/12
- [x] (Treasury: pallet_treasury::Pallet)
- [x] (Tips: pallet_tips::Pallet)
- [x] (Bounties: pallet_bounties::Pallet)
- [x] (Democracies: Democracy: pallet_democracy::Pallet)
- [ ] (Society: pallet_society::Pallet)
- [ ] (Recovery: pallet_recovery::Pallet)
- [ ] (Multisig: pallet_multisig::Pallet)

## No needed
- [x] (DarwiniaHeaderMmr: darwinia_header_mmr::Pallet)
- [x] (Council: pallet_collective::<Instance1>::Pallet)
- [x] (TechnicalCommittee: pallet_collective::<Instance2>::Pallet)
- [x] (PhragmenElection: pallet_elections_phragmen::Pallet)
- [x] (TechnicalMembership: pallet_membership::<Instance1>::Pallet)
- [x] (Scheduler: pallet_scheduler::Pallet)

## Not sure
- [ ] (DarwiniaFeeMarket: pallet_fee_market::<Instance1>::Pallet)
- [ ] (CrabParachainFeeMarket::pallet_fee_market::<Instance2>::Pallet)

**Comment by HackFisher** [comment]
```
		pub free_kton: Balance,
		pub reserved_kton: Balance,
```

kton in account data can be removed.
