### ISSUE TITLE
Set HRMP channels genesis state

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-2.0#275]
- [ ] Open some HRMP channels on MoonbaseAlpha

**Comment by jiguantong** [comment]
We should pay attention to these two states:
- `parachainSystem.lastHrmpMqcHeads`
- `parachainSystem.lastDmqMqcHead`

**Comment by jiguantong** [comment]
> We should pay attention to these two states:
> 
> * `parachainSystem.lastHrmpMqcHeads`
> * `parachainSystem.lastDmqMqcHead`

We can keep these two states consistent with the old parachain in genesis, and then [they will be updated automatically](https://github.com/paritytech/cumulus/blob/polkadot-v0.9.37/pallets/parachain-system/src/lib.rs#L905)

**Comment by AurevoirXavier** [comment]
Test passed on Pangolin local.

```
0x45323df7cc47150b3930e2666b0aa313911a5dd3f1155f5b7d0c5aa102a757f9: Raw
0x821341534e0bc96c4a3a48d33b56de2a19ab2c280410aa0fde78312c2f6cd5df

0x45323df7cc47150b3930e2666b0aa3133dca42deb008c6559ee789c9b9f70a2c: Raw
0x04d00700000000000000000000000000000000000000000000000000000000000000000000
```
