### ISSUE TITLE
New faucets for testnets

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-2.0#307]
Darwinia 2.0 needs new faucets for Pangolin2 and Pangoro2.

**Comment by boundless-forest** [comment]
The original faucet is part of the `Darwinia Apps`, which will no longer be maintained after the launch of the darwinia 2.0. We need to refine the usage of faucets obviously. For example, integrate it into the Telegram, Discord or somewhere.

**Comment by wuminzhe** [comment]
Is there any faucet service that we can build on?

**Comment by boundless-forest** [comment]
https://github.com/darwinia-network/faucet
