### ISSUE TITLE
Derive account algorithm

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-2.0#41]
Should we keep the same chain id?

Or, use `H160` as native account type #15.

**Comment by AsceticBear** [comment]
> Should we keep the same chain id?

Do you mean the evm chain id?  I think we should keep the same as the darwinia 1.0 design to reduce the burden of application developers.

**Comment by HackFisher** [comment]
use the same chain id, but for the used nonces should be kept.

Refer spec draft
