### ISSUE TITLE
How to deal with the opened HRMP channels

### ISSUE THREAD

**Issue by jiguantong** [darwinia-network/darwinia-2.0#45]
https://boundless-forest.notion.site/solo-para-38780f3df52b4b52802822be05ef56b5
Will HRMP channels be cleaned up when we merge darwinia-2.0 into Darwinia Parachain?

**Comment by jiguantong** [comment]
If it will clean up the channels, we need to close channels before merging to get back the reserved tokens. @AurevoirXavier

**Comment by AurevoirXavier** [comment]
All the channels will be kept.
