### ISSUE TITLE
How to merge system account info 

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-2.0#51]
```
if account.exist_in_solo() {
    nonce = solo.nonce;
    ..consumers, providers, sufficients
} else {
    nonce = para.nonce;
    ..consumers, providers, sufficients
}
```

**Comment by AurevoirXavier** [comment]
I think we could clean the nonce.

Because we are going to migrate the address format to `H160`.

**Comment by AsceticBear** [comment]
> I think we could clean the nonce.
> 
> Because we are going to migrate the address format to `H160`.

I don't think you can do this. In darwinia 1.0, the evm account > substrate account, so the nonce of the evm account is essentially the nonce of the substrate account. In the design of darwinia 2.0, I understand that the original evm account does not need to claim, and the substrate account corresponding to this account is itself derive, so you can reverse the evm account from the substrate account and migrate the account info over. If the nonce is cleared out, the original evm accounts will not work and there is a risk of a nonce replay attack.

**Comment by HackFisher** [comment]
> I think we could clean the nonce.
> 
> 
> 
> Because we are going to migrate the address format to `H160`.

We need to split evm related address from other substrate account, the nonce for the evm addresses(match the format) shoul be kept.

**Comment by boundless-forest** [comment]
This has been fixed. Close it.

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia-2.0/blob/2e78ca7741263f536ba08ff73ec590c2bf0475bc/tool/state-processor/src/system/mod.rs#L44-L47

**Comment by AurevoirXavier** [comment]
#187.
