### ISSUE TITLE
Abnormal Base Fee

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-2.0#62]
<img width="288" alt="image" src="https://user-images.githubusercontent.com/16152305/157792838-ab285cae-6b1b-401c-806e-60bed5055fa2.png">

**Comment by AurevoirXavier** [comment]
Any updates?

**Comment by boundless-forest** [comment]
Sorry for the delay. After https://github.com/paritytech/frontier/pull/892 merged, we do not need the base-fee pallet anymore.

We can fix this after bumping the substrate version to 0.9.34+.
