### ISSUE TITLE
Reap the Leger After Unbonding All

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-2.0#63]
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/16152305/170958622-baf5015a-27b4-448d-b92a-7bbe6fbf8787.png">

And we need some migrations to clean the Darwinia and Crab's staking storage.

**Comment by HackFisher** [comment]
Only require some review to tell whether we still need to do this clean or not.

**Comment by AurevoirXavier** [comment]
It is fixed in the latest staking implementation.
