### ISSUE TITLE
Reserve precompile addresses from [1026, 1536) For ERC20 precompiles (asset pallet) 

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-2.0#65]
1026 will be used for KTON, using assetERC20 asset.

The ethereum address of asset will be equal to asset_id in asset pallet.

[1536, 2048) will be reserved for other stable precompiles

asset_id will start from 1026 too.

**Comment by AsceticBear** [comment]
> [1536, 2048) will be reserved for other stable precompiles

I want to confirm the address range again here. The start of the reserved stable precompiles is `1526` instead of `1536`.  We reserve 500 spaces for assets precompile, 1026 + 500 = 1526. @HackFisher

**Comment by HackFisher** [comment]
> > [1536, 2048) will be reserved for other stable precompiles
> 
> 
> 
> I want to confirm the address range again here. The start of the reserved stable precompiles is `1526` instead of `1536`.  We reserve 500 spaces for assets precompile, 1026 + 500 = 1526. @HackFisher 

1024+512 = 1526, this is how 1526 generated, let's use bit segments.
