### ISSUE TITLE
Update Proxy Filter

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-2.0#77]
> https://github.com/darwinia-network/darwinia/blob/main/runtime/crab/src/pallets/proxy.rs
> https://github.com/darwinia-network/darwinia/blob/main/runtime/darwinia/src/pallets/proxy.rs

Some newly added pallets are missed.

**Comment by ECJ222** [comment]
is this issue open for anyone to work on? @AurevoirXavier

**Comment by AurevoirXavier** [comment]
> is this issue open for anyone to work on? @AurevoirXavier

Sorry for the late response.

I think nope.

Currently, we are redesigning the runtime.

**Comment by ECJ222** [comment]
> > is this issue open for anyone to work on? @AurevoirXavier
> 
> Sorry for the late response.
> 
> I think nope.
> 
> Currently, we are redesigning the runtime.

Okay
